motion_plan:
  - type : "linear"
    goal : 0.8
    curve_radius : 0.0
  - type : "curve"
    goal : 90.0   # degree
    curve_radius : 2.5  # stabilizer
    # "curve_radius" : 0.87  # rear wheel free
  - type : "linear"
    goal : 5.0
    curve_radius : 0
p_dist : 0.15  # distance between tugbot wheel center and pivot point of gripper
c_dist : 1.8  #ã€€distance between pivot point of gripper and cargo wheel center, case of rear wheels free
cf_dist : 0.20  # distance between pivot point of gripper and cart front edge
cart_length : 1.7
cart_width : 1.1
x0 : 0.15  # initial x of tugbot wheel center
y0 : -0.45  # initial y of tugbot wheel center
init_theta : 0.0 # initial tugbot angle, degree
init_phi : 0.0  # initial cargo angle, degree