motion_plan:
  - type : "linear"
    goal : 0.1
    curve_radius : 0.0
  - type : "curve"
    goal : 60.0   # degree
    curve_radius : 1.8  # stabilizer
    # "curve_radius" : 0.87  # rear wheel free
  - type : "curve"
    goal : -60.0   # degree
    curve_radius : 1.8  # stabilizer
    # "curve_radius" : 0.87  # rear wheel free
  - type : "linear"
    goal : 2.0
    curve_radius : 0
p_dist : 0.0  # distance between tugbot wheel center and pivot point of gripper
c_dist : 0.85  #ã€€distance between pivot point of gripper and cargo wheel center, case of rear wheels free
p2_dist : 1.725  # distance between pivot point of gripper and pivot point of 2nd cart
c2_dist : 0.225  # distance between pivot point of 2nd cart and 2nd cart wheel center
cf_dist : 0.45  # distance between pivot point of gripper and cart front edge
cf2_dist : 0.175  # distance between pivot point of 2nd cart and 2nd cart front edge
cart_length : 1.1
cart_width : 0.8
x0 : 4.1  # initial x of tugbot wheel center
y0 : 2.0  # initial y of tugbot wheel center
init_theta : 180.0 # initial tugbot angle, degree
init_phi : 180.0  # initial cargo angle, degree
init_phi2 : 180.0  # initial 2nd cart angle, degree