motion_plan:
  # - type : "linear"
  #   goal : 0.1
  #   curve_radius : 0.0
  - type : "curve"
    goal : 90.0   # degree
    curve_radius : 3.9  # stabilizer
    # "curve_radius" : 0.87  # rear wheel free
  - type : "linear"
    goal : 1.1
    curve_radius : 0
p_dist : 0.15  # distance between tugbot wheel center and pivot point of gripper
c_dist : 0.6  #ã€€distance between pivot point of gripper and cargo wheel center, case of rear wheels free
cf_dist : 0.20  # distance between pivot point of gripper and cart front edge
cart_length : 2.25
cart_width : 1.286
x0 : -0.7  # initial x of tugbot wheel center
y0 : 0.08  # initial y of tugbot wheel center
init_theta : 0.0 # initial tugbot angle, degree
init_phi : 0.0  # initial cargo angle, degree