motion_plan:
  - type : "linear"
    goal : 3.00
    curve_radius : 0.0
  - type : "curve"
    goal : 90.0   # degree
    curve_radius : 1.4  # stabilizer
    # "curve_radius" : 0.87  # rear wheel free
  - type : "linear"
    goal : 4.5
    curve_radius : 0
p_dist : 0.0  # distance between tugbot wheel center and pivot point of gripper
c_dist : 0.85  #ã€€distance between pivot point of gripper and cargo wheel center, case of stabilizer
cf_dist : 0.45  # distance between pivot point of gripper and cart front edge
cart_length : 1.453
cart_width : 0.685
x0 : -1.3  # initial x of tugbot wheel center
y0 : -0.0  # initial y of tugbot wheel center
init_theta : 0.0 # initial tugbot angle, degree
init_phi : 0.0  # initial cargo angle, degree