motion_plan:
  - type : "linear"
    goal : 2.05
    curve_radius : 0.0
  - type : "curve"
    goal : 90.0   # degree
    curve_radius : 1.2  # stabilizer
    # "curve_radius" : 0.87  # rear wheel free
  - type : "linear"
    goal : 2.5
    curve_radius : 0
p_dist : 0.0  # distance between tugbot wheel center and pivot point of gripper
c_dist : 0.85  #ã€€distance between pivot point of gripper and cargo wheel center, case of stabilizer
cf_dist : 0.45  # distance between pivot point of gripper and cart front edge
cart_length : 0.8
cart_width : 0.6
x0 : 1.5  # initial x of tugbot wheel center
y0 : 1.0  # initial y of tugbot wheel center
init_theta : -90 # initial tugbot angle, degree
init_phi : -90  # initial cargo angle, degree