motion_plan:
  - type : "linear"
    goal : 1.0
    curve_radius : 0.0
  - type : "curve"
    goal : 180.0   # degree
    curve_radius : 1.45  # stabilizer
    # "curve_radius" : 0.87  # rear wheel free
  - type : "linear"
    goal : 2.5
    curve_radius : 0
p_dist : 0.0  # distance between tugbot wheel center and pivot point of gripper
c_dist : 0.85  #ã€€0.45 + 0.4, distance between pivot point of gripper and cargo wheel center, case of 4 wheels free with stabilizer
# c_dist : 0.50  # 0.45 + 0.05, distance between pivot point of gripper and cargo wheel center, case of rear wheels free
cf_dist : 0.45  # distance between pivot point of gripper and cart front edge
cart_length : 0.84  # for cargo cart
cart_width : 0.65  # for cargo cart
x0 : 0.125  # initial x of tugbot wheel center
y0 : 0.0  # initial y of tugbot wheel center
init_theta : 90.0 # initial tugbot angle, degree
init_phi : 90.0  # initial cargo angle, degree